development:
  username: 'choresapplication@gmail.com'
  password: 'vp-mgsnaJFW6GP6LaZ0LmA'

test:
  username: 'choresapplication@gmail.com'
  password: 'vp-mgsnaJFW6GP6LaZ0LmA'

production:
  username: 'app40625377@heroku.com'
  password: 'ErbV7HNw1GBqLIJrre0Ajg'