development:
  username: 'choresapplication@gmail.com'
  password: 'vp-mgsnaJFW6GP6LaZ0LmA'

test:
  username: 'choresapplication@gmail.com'
  password: 'vp-mgsnaJFW6GP6LaZ0LmA'

production:
  username: 'choresapplication@gmail.com'
  password: 'vp-mgsnaJFW6GP6LaZ0LmA'  